version: "3.3"
services:
  ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
  ###############################################################################
  # ResetService
  ###############################################################################
  resetservice:
    image: 'ghcr.io/microrealestate/microrealestate/resetservice:${MRE_VERSION:-latest}'
    build:
      context: .
      dockerfile: services/resetservice/dev.Dockerfile
    environment:
      - NODE_ENV
      - PORT=$RESETSERVICE_PORT
      - LOGGER_LEVEL
      - REDIS_URL
      - REDIS_PASSWORD
      - MONGO_URL
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/resetservice:/usr/app/services/resetservice
      - /usr/app/node_modules
      - /usr/app/services/resetservice/node_modules
      - /usr/app/services/resetservice/dist
    expose:
      - "$RESETSERVICE_PORT"
    ports:
      - "$RESETSERVICE_DEBUG_PORT:9230"
    networks:
      - net
    depends_on:
      - redis
      - mongo
  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    build:
      context: .
      dockerfile: services/gateway/dev.Dockerfile
    environment:
      - RESETSERVICE_URL
    volumes:
      - ./types:/usr/app/types
      - ./services/typed-common:/usr/app/services/typed-common
      - ./services/gateway:/usr/app/services/gateway
      - /usr/app/node_modules
      - /usr/app/services/gateway/node_modules
      - /usr/app/services/gateway/dist
    ports:
      - "$GATEWAY_DEBUG_PORT:9225"
    depends_on:
      - resetservice
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: .
      dockerfile: services/authenticator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/authenticator:/usr/app/services/authenticator
      - /usr/app/node_modules
      - /usr/app/services/authenticator/node_modules
      - /usr/app/services/authenticator/dist
    ports:
      - "$AUTHENTICATOR_DEBUG_PORT:9226"
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: .
      dockerfile: services/pdfgenerator/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/pdfgenerator:/usr/app/services/pdfgenerator
      - /usr/app/node_modules
      - /usr/app/services/pdfgenerator/node_modules
      - /usr/app/services/pdfgenerator/dist
    ports:
      - "$PDFGENERATOR_DEBUG_PORT:9227"
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: .
      dockerfile: services/emailer/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/emailer:/usr/app/services/emailer
      - /usr/app/node_modules
      - /usr/app/services/emailer/node_modules
      - /usr/app/services/emailer/dist
    ports:
      - "$EMAILER_DEBUG_PORT:9228"
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: .
      dockerfile: services/api/dev.Dockerfile
    volumes:
      - ./services/common:/usr/app/services/common
      - ./services/api:/usr/app/services/api
      - /usr/app/node_modules
      - /usr/app/services/api/node_modules
      - /usr/app/services/api/dist
    ports:
      - "$API_DEBUG_PORT:9229"
  ###############################################################################
  # tenantapi
  ###############################################################################
  tenantapi:
    build:
      context: .
      dockerfile: services/tenantapi/dev.Dockerfile
    volumes:
      - ./types:/usr/app/types
      - ./services/typed-common:/usr/app/services/typed-common
      - ./services/tenantapi:/usr/app/services/tenantapi
      - /usr/app/node_modules
      - /usr/app/services/tenantapi/node_modules
      - /usr/app/services/tenantapi/dist
    ports:
      - "$TENANTAPI_DEBUG_PORT:9240"
  ###############################################################################
  # Landlord frontend
  ###############################################################################
  landlord-frontend:
    build:
      context: .
      dockerfile: webapps/landlord/dev.Dockerfile
    volumes:
      - ./webapps/commonui:/usr/app/webapps/commonui
      - ./webapps/landlord:/usr/app/webapps/landlord
      - /usr/app/node_modules
      - /usr/app/webapps/landlord/node_modules
      - /usr/app/webapps/landlord/.next
  ###############################################################################
  # Tenant frontend
  ###############################################################################
  tenant-frontend:
    build:
      context: .
      dockerfile: webapps/tenant/dev.Dockerfile
    volumes:
      - ./types:/usr/app/types
      - ./webapps/commonui:/usr/app/webapps/commonui
      - ./webapps/tenant:/usr/app/webapps/tenant
      - /usr/app/node_modules
      - /usr/app/webapps/tenant/node_modules
      - /usr/app/webapps/tenant/.next
